### PR TITLE
Fixes for repeated deletes with xcursor

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**
On DUPSORT DBs, must initialize xcursor regardless of whether
caller requested its data.

### CODE REVIEW

**Comment by AlexeyAkhunov** [comment]
Is this change going to go into one of the LMDB releases?

**Comment by AndreaLanfranchi** [comment]
This PR is to merge current Howard's master in sync.
It seems to me is in release 0.9.27
This torquem repo is however not directly linked to our work:
- silkworm uses huntered release
- tg points to https://github.com/ledgerwatch/lmdb-go/tree/master/lmdb

Would like to use this repo to experiment.

**Comment by yperbasis** [comment]
@AndreaLanfranchi We should use the mdb.RE/0.9 branch, not master. The two branches are very different.

**Comment by AndreaLanfranchi** [comment]
Thank you @yperbasis . I missed that

**Comment by AndreaLanfranchi** [comment]
Should not be still opened

**Pull request closed without merging**
